# Generated by Django 5.0.3 on 2024-08-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_remove_order_total_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_total',
        ),
    ]
