# Generated by Django 5.0.3 on 2024-08-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_productdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetail',
            new_name='Product_detail',
        ),
    ]
