# Generated by Django 5.0.3 on 2024-08-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_rename_productdetail_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='first_app.OrderItem', to='first_app.product'),
        ),
    ]
